version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: oasis_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: oasisdb
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: oasis_backend
    restart: always
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=1234
      - DB_NAME=oasisdb
      - DB_PORT=3306
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: oasis_frontend
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - backend
