apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "15"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"oasis-backend","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"oasis-backend"}},"template":{"metadata":{"labels":{"app":"oasis-backend"}},"spec":{"containers":[{"env":[{"name":"DB_HOST","value":"oasis-db"},{"name":"DB_PASS","valueFrom":{"secretKeyRef":{"key":"db_password","name":"oasis-secrets"}}},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt_secret","name":"oasis-secrets"}}}],"envFrom":[{"configMapRef":{"name":"oasis-config"}}],"image":"tartarusboss/oasis-backend:latest","name":"backend","ports":[{"containerPort":4000}]}]}}}}
  creationTimestamp: "2025-11-10T01:07:49Z"
  generation: 15
  name: oasis-backend
  namespace: default
  resourceVersion: "6304"
  uid: c1a207d9-a90b-4b13-851c-d80dc4871090
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: oasis-backend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-11-09T21:01:14-05:00"
      labels:
        app: oasis-backend
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: oasis-db
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              key: db_password
              name: oasis-secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_secret
              name: oasis-secrets
        envFrom:
        - configMapRef:
            name: oasis-config
        image: test-build:latest`n        imagePullPolicy: IfNotPresent
        imagePullPolicy: Always
        name: backend
        ports:
        - containerPort: 4000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-11-10T01:07:51Z"
    lastUpdateTime: "2025-11-10T01:07:51Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-11-10T01:07:49Z"
    lastUpdateTime: "2025-11-10T02:08:39Z"
    message: ReplicaSet "oasis-backend-5d6f4d6b49" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 15
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
