apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasis-backend
  namespace: default
spec:
  selector:
    matchLabels:
      app: oasis-backend
  template:
    metadata:
      labels:
        app: oasis-backend
    spec:
      containers:
        - name: backend
          image: test-build:latest
          imagePullPolicy: IfNotPresent
