apiVersion: apps/v1
kind: Deployment
metadata:
  name: oasis-backend
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: backend
          image: test-build:latest
          imagePullPolicy: IfNotPresent
